name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: .

      - name: Build app for current OS
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            npm run dist -- --linux AppImage
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            npm run dist -- --win
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            npm run dist -- --mac
          fi
        working-directory: .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zametka-${{ matrix.os }}
          path: dist/
